# Generated by Django 5.0.4 on 2025-08-31 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('sender', models.CharField(max_length=100)),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date received')),
                ('category', models.CharField(blank=True, choices=[('produtivo', 'Produtivo'), ('improdutivo', 'Improdutivo')], max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('suggested_response', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
    ]
